// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/messageId.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MessageId {

  /// <summary>Holder for reflection information generated from proto/messageId.proto</summary>
  public static partial class MessageIdReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/messageId.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVwcm90by9tZXNzYWdlSWQucHJvdG8SCW1lc3NhZ2VJZCrrAwoJTWVzc2Fn",
            "ZUlkEggKBE5vbmUQABIWChBDMlNfQ3JlYXRlUGxheWVyENGGAxIWChBTMkNf",
            "Q3JlYXRlUGxheWVyENKGAxIPCglDMlNfTG9naW4Q04YDEg8KCVMyQ19Mb2dp",
            "bhDUhgMSFQoPQzJHU19FbnRlclNlbmNlEKGNBhIVCg9HUzJDX0VudGVyU2Vu",
            "Y2UQoo0GEhUKD0MyR1NfUGxheWVyTW92ZRCjjQYSFQoPR1MyQ19QbGF5ZXJN",
            "b3ZlEKSNBhIWChBDMkdTX1BsYXllckxlYXZlEKWNBhIWChBHUzJDX1BsYXll",
            "ckxlYXZlEKaNBhIUCg5DMkdTX0FkZEZyaWVuZBCnjQYSFAoOR1MyQ19BZGRG",
            "cmllbmQQqI0GEhQKDkMyR1NfRGVsRnJpZW5kEKmNBhIUCg5HUzJDX0RlbEZy",
            "aWVuZBCqjQYSFgoQQzJHU19TZW5kQ2hhdE1zZxCrjQYSFgoQR1MyQ19TZW5k",
            "Q2hhdE1zZxCsjQYSGwoVQzJHU19PTkxpbmVQbGF5ZXJMaXN0EK2NBhIbChVH",
            "UzJDX09OTGluZVBsYXllckxpc3QQro0GEhkKE0MyR1NfUGxheWVyU3RvcE1v",
            "dmUQr40GEhkKE0dTMkNfUGxheWVyU3RvcE1vdmUQsI0GQgxaCi9tZXNzYWdl",
            "SWRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MessageId.MessageId), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MessageId {
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("C2S_CreatePlayer")] C2SCreatePlayer = 50001,
    [pbr::OriginalName("S2C_CreatePlayer")] S2CCreatePlayer = 50002,
    [pbr::OriginalName("C2S_Login")] C2SLogin = 50003,
    [pbr::OriginalName("S2C_Login")] S2CLogin = 50004,
    /// <summary>
    ///player
    /// </summary>
    [pbr::OriginalName("C2GS_EnterSence")] C2GsEnterSence = 100001,
    [pbr::OriginalName("GS2C_EnterSence")] Gs2CEnterSence = 100002,
    [pbr::OriginalName("C2GS_PlayerMove")] C2GsPlayerMove = 100003,
    [pbr::OriginalName("GS2C_PlayerMove")] Gs2CPlayerMove = 100004,
    [pbr::OriginalName("C2GS_PlayerLeave")] C2GsPlayerLeave = 100005,
    [pbr::OriginalName("GS2C_PlayerLeave")] Gs2CPlayerLeave = 100006,
    [pbr::OriginalName("C2GS_AddFriend")] C2GsAddFriend = 100007,
    [pbr::OriginalName("GS2C_AddFriend")] Gs2CAddFriend = 100008,
    [pbr::OriginalName("C2GS_DelFriend")] C2GsDelFriend = 100009,
    [pbr::OriginalName("GS2C_DelFriend")] Gs2CDelFriend = 100010,
    [pbr::OriginalName("C2GS_SendChatMsg")] C2GsSendChatMsg = 100011,
    [pbr::OriginalName("GS2C_SendChatMsg")] Gs2CSendChatMsg = 100012,
    [pbr::OriginalName("C2GS_ONLinePlayerList")] C2GsOnlinePlayerList = 100013,
    [pbr::OriginalName("GS2C_ONLinePlayerList")] Gs2COnlinePlayerList = 100014,
    [pbr::OriginalName("C2GS_PlayerStopMove")] C2GsPlayerStopMove = 100015,
    [pbr::OriginalName("GS2C_PlayerStopMove")] Gs2CPlayerStopMove = 100016,
  }

  #endregion

}

#endregion Designer generated code
